---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scm
  name: config-client-deployment
  labels:
    app: config-client
spec:
  selector:
    matchLabels:
      app: config-client
  template:
    metadata:
      labels:
        app: config-client
    spec:
      containers:
        - name: config-client
          imagePullPolicy: Always
          image: gcr.io/pgtm-jlong/config-client
---
apiVersion: v1
kind: Service
metadata:
  namespace: scm
  name: config-client-service
spec:

  selector:
    app: config-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


